"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3
shell_integration = true

[transient_prompt]
    background = "transparent"
    foreground = "#6A7FEA"
    template = "[#] ÔÑÖ "

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = 'ÓÆô {{ .UserName }} on'
    foreground = '#B4BEFE'
    background = ''
    type = 'session'

  [[blocks.segments]]
    style = 'plain'
    template = ' ÔÑï {{ .Path }} '
    foreground = '#6A7FEA'
    background = ''
    type = 'path'

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'letter'
      # style = 'agnoster'
      # style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .UpstreamIcon }} {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{end}}{{ if gt .Behind 0}}‚Üì{{end}}{{ if gt .Ahead 0 }}‚Üë{{end}}{{ if gt .StashCount 0 }} Ó≠ã {{ .StashCount }}{{ end }} '
    foreground = '#14A5AE'
    powerline_symbol = 'ÓÇ∞'
    background = ''
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    style = 'plain'
    template = '( Óàµ {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} ){{ end }}{{ end }}'
    foreground = '#D0679D'
    background = ''
    type = 'python'

    [blocks.segments.properties]
      display_mode = 'environment'
      fetch_virtual_env = true
      folder_name_fallback = false

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .CurrentDate | date "15:04:05" }}'
    foreground = '#B8C4C7'
    background = ''
    type = 'time'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{.Icon}} '
    foreground = '#6A7FEA'
    background = ''
    type = 'os'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = 'Óéø '
    foreground = '#cd5e42'
    background = ''
    type = 'root'

  [[blocks.segments]]
    style = 'plain'
    template = '['
    foreground = '#6A7FEA'
    background = ''
    type = 'text'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óàµ  '
    foreground = '#50C878'
    background = ''
    type = 'python'

    [blocks.segments.properties]
      display_mode = 'files'

  [[blocks.segments]]
    style = 'plain'
    template = ' ‚Ä≠Ô≥ë '
    foreground = '#7FD5EA'
    background = ''
    type = 'go'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óö© '
    foreground = '#342311'
    background = ''
    type = 'zig'


  [[blocks.segments]]
    style = 'plain'
    template = ' Óúò '
    foreground = '#6CA35E'
    background = ''
    type = 'node'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óû® '
    foreground = '#D3672C'
    background = ''
    type = 'rust'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óò≠ '
    foreground = '#422251'
    background = ''
    type = 'elixir'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óâñ '
    foreground = '#A51C30'
    background = ''
    type = 'java'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óòà '
    foreground = '#75715E'
    background = ''
    type = 'php'

  [[blocks.segments]]
    style = 'plain'
    template = ' <b>K</b> '
    foreground = '#906cff'
    background = ''
    type = 'kotlin'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óûë '
    foreground = '#D32F2F'
    background = ''
    type = 'ruby'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óòü  '
    foreground = '#8A3FFC'
    background = ''
    type = 'haskell'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óùø  '
    foreground = '#007ACC'
    background = ''
    type = 'dotnet'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óùì '
    foreground = '#D9534F'
    background = ''
    type = 'angular'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óû∫ '
    foreground = '#61DAFB'
    background = ''
    type = 'react'

    [blocks.segments.properties]
      extensions = ['*.jsx', '*.tsx']

  [[blocks.segments]]
    style = 'plain'
    template = ' Óòû Óòù '
    foreground = '#007ACC'
    background = ''
    type = 'cmake'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óô∫ '
    foreground = '#d08770'
    background = ''
    type = 'ocaml'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óù© '
    foreground = '#4063D8'
    background = ''
    type = 'perl'

  [[blocks.segments]]
    style = 'plain'
    template = ' R '
    foreground = 'lightblue'
    background = ''
    type = 'r'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óöû '
    foreground = '#1E90FF'
    background = ''
    type = 'vala'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óûò '
    foreground = '#FFD700'
    background = ''
    type = 'dart'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óùï '
    foreground = '#FFA500'
    background = ''
    type = 'swift'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óò§ '
    foreground = '#8A2BE2'
    background = ''
    type = 'julia'

  [[blocks.segments]]
    style = 'plain'
    template = ' Óò† '
    foreground = '#56B6C2'
    background = ''
    type = 'lua'

  [[blocks.segments]]
    style = 'plain'
    template = 'ÓûÅ '
    foreground = '#F7DF1E'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.js', '*.cjs', '*.mjs']

  [[blocks.segments]]
    type = 'mojo'
    style = 'plain'
    foreground = '#100e23'
    background = ''
    template = ' üî• '

  [[blocks.segments]]
    style = 'plain'
    template = ' Óò® '
    foreground = '#007ACC'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.ts', '*.cts', '*.mts']

  [[blocks.segments]]
    style = 'plain'
    template = ' Ôíâ '
    foreground = '#E5A50A'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.sh', '.bashrc', '*.bash']
      folders = ['*.sh']

  [[blocks.segments]]
    style = 'plain'
    template = ' ÔáÄ '
    foreground = '#4479A1'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.sql', '*.db', '*.sqlite']

  [[blocks.segments]]
    style = 'plain'
    template = ' Ôåà '
    foreground = '#0db7ed'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['Dockerfile', 'docker-compose.yml', '*Dockerfile*']

  [[blocks.segments]]
    style = 'plain'
    template = ' Óòï '
    foreground = '#ff79c6'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['.zshrc', '.vimrc', '.editorconfig', '*.conf', '*.toml']

  [[blocks.segments]]
    style = 'plain'
    template = ' Óú∂ '
    foreground = '#e34c26'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.html']

  [[blocks.segments]]
    style = 'plain'
    template = ' Óùâ '
    foreground = '#563d7c'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.css', '*.scss', '*.sass']

  [[blocks.segments]]
    style = 'plain'
    template = ' ÔáÖ '
    foreground = '#FFD700'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.png', '*.jpg', '*.jpeg', '*.gif', '*.svg']

  [[blocks.segments]]
    style = 'plain'
    template = ' üé¨ '
    foreground = '#FF4500'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.mp4', '*.mkv', '*.avi', '*.mov', '*.wmv']

  [[blocks.segments]]
    style = 'plain'
    template = ' Ô¢É '
    foreground = '#2980B9'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.mp3', '*.wav', '*.flac']

  [[blocks.segments]]
    style = 'plain'
    template = ' Ôêê '
    foreground = '#8E44AD'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.zip', '*.tar', '*.gz', '*.rar', '*.7p']

  [[blocks.segments]]
    style = 'plain'
    template = ' ÔÄ± '
    foreground = '#F39C12'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['*.ttf', '*.otf', '*.woff']

  [[blocks.segments]]
    style = 'plain'
    template = ' ÔåÉ '
    foreground = '#3B82F6'
    background = ''
    type = 'node'

    [blocks.segments.properties]
      extensions = ['.pkg.tar.zst', '.pkg.tar.xz', '.pkg.tar.gz', '*.pacman']

  [[blocks.segments]]
    style = 'plain'
    template = '] ÔÑÖ '
    foreground = '#6A7FEA'
    background = ''
    type = 'text'

