"$schema"                 = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
async                     = true
enable_cursor_positioning = true
final_space               = true
shell_integration         = true
version                   = 4

[transient_prompt]
    background = 'transparent'
    foreground = '#6A7FEA'
    template   = '[#] ï„… '

[[blocks]]
    alignment = 'left'
    type      = 'prompt'

    [[blocks.segments]]
        foreground = '#B4BEFE'
        style      = 'plain'
        template   = 'î®™ {{ .UserName }} on'
        type       = 'session'

    [[blocks.segments]]
        foreground = '#6A7FEA'
        style      = 'plain'
        template   = ' ï„• {{ .Path }} '
        type       = 'path'

    [[blocks.segments]]
        foreground       = '#14A5AE'
        powerline_symbol = 'î‚°'
        style            = 'plain'
        template         = '{{ .UpstreamIcon }} {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{end}}{{ if gt .Behind 0}}â†“{{end}}{{ if gt .Ahead 0 }}â†‘{{end}}{{ if gt .StashCount 0 }} î­‹ {{ .StashCount }}{{ end }} '
        type             = 'git'

    [[blocks.segments]]
        foreground = '#D0679D'
        style      = 'plain'
        template   = '( îˆµ {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} ){{ end }}{{ end }}'
        type       = 'python'

[[blocks]]
    alignment = 'right'
    type      = 'prompt'

    [[blocks.segments]]
        foreground = '#B8C4C7'
        style      = 'plain'
        template   = '{{ .CurrentDate | date "15:04:05" }}'
        type       = 'time'

    [[blocks.segments]]
        foreground = '#6A7FEA'
        style      = 'plain'
        template   = ' {{.Icon}} '
        type       = 'os'

[[blocks]]
    alignment = 'left'
    newline   = true
    type      = 'prompt'

    [[blocks.segments]]
        foreground = '#cd5e42'
        style      = 'plain'
        template   = 'î¿ '
        type       = 'root'

    [[blocks.segments]]
        foreground = '#6A7FEA'
        style      = 'plain'
        template   = '['
        type       = 'text'

    [[blocks.segments]]
        foreground = '#50C878'
        style      = 'plain'
        template   = ' îˆµ  '
        type       = 'python'

    [[blocks.segments]]
        foreground = '#7FD5EA'
        style      = 'plain'
        template   = ' î˜§ '
        type       = 'go'

    [[blocks.segments]]
        foreground = '#342311'
        style      = 'plain'
        template   = ' îš© '
        type       = 'zig'

    [[blocks.segments]]
        foreground = '#6CA35E'
        style      = 'plain'
        template   = ' îœ˜ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#D3672C'
        style      = 'plain'
        template   = ' î¨ '
        type       = 'rust'

    [[blocks.segments]]
        foreground = '#422251'
        style      = 'plain'
        template   = ' î˜­ '
        type       = 'elixir'

    [[blocks.segments]]
        foreground = '#A51C30'
        style      = 'plain'
        template   = ' î‰– '
        type       = 'java'

    [[blocks.segments]]
        foreground = '#75715E'
        style      = 'plain'
        template   = ' î˜ˆ '
        type       = 'php'

    [[blocks.segments]]
        foreground = '#906cff'
        style      = 'plain'
        template   = ' <b>K</b> '
        type       = 'kotlin'

    [[blocks.segments]]
        foreground = '#D32F2F'
        style      = 'plain'
        template   = ' î‘ '
        type       = 'ruby'

    [[blocks.segments]]
        foreground = '#8A3FFC'
        style      = 'plain'
        template   = ' î˜Ÿ  '
        type       = 'haskell'

    [[blocks.segments]]
        foreground = '#007ACC'
        style      = 'plain'
        template   = ' î¿  '
        type       = 'dotnet'

    [[blocks.segments]]
        foreground = '#D9534F'
        style      = 'plain'
        template   = ' î“ '
        type       = 'angular'

    [[blocks.segments]]
        foreground = '#61DAFB'
        style      = 'plain'
        template   = ' îº '
        type       = 'react'

    [[blocks.segments]]
        foreground = '#007ACC'
        style      = 'plain'
        template   = ' î˜ î˜ '
        type       = 'cmake'

    [[blocks.segments]]
        foreground = '#d08770'
        style      = 'plain'
        template   = ' î™º '
        type       = 'ocaml'

    [[blocks.segments]]
        foreground = '#4063D8'
        style      = 'plain'
        template   = ' î© '
        type       = 'perl'

    [[blocks.segments]]
        foreground = '#ADD8E6'
        style      = 'plain'
        template   = ' R '
        type       = 'r'

    [[blocks.segments]]
        foreground = '#1E90FF'
        style      = 'plain'
        template   = ' îš '
        type       = 'vala'

    [[blocks.segments]]
        foreground = '#FFD700'
        style      = 'plain'
        template   = ' î˜ '
        type       = 'dart'

    [[blocks.segments]]
        foreground = '#FFA500'
        style      = 'plain'
        template   = ' î• '
        type       = 'swift'

    [[blocks.segments]]
        foreground = '#8A2BE2'
        style      = 'plain'
        template   = ' î˜¤ '
        type       = 'julia'

    [[blocks.segments]]
        foreground = '#56B6C2'
        style      = 'plain'
        template   = ' î˜  '
        type       = 'lua'

    [[blocks.segments]]
        foreground = '#F7DF1E'
        style      = 'plain'
        template   = 'î '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#100e23'
        style      = 'plain'
        template   = ' ğŸ”¥ '
        type       = 'mojo'

    [[blocks.segments]]
        foreground = '#007ACC'
        style      = 'plain'
        template   = ' î˜¨ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#E5A50A'
        style      = 'plain'
        template   = ' ï’‰ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#4479A1'
        style      = 'plain'
        template   = ' ï‡€ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#0db7ed'
        style      = 'plain'
        template   = ' ïŒˆ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#ff79c6'
        style      = 'plain'
        template   = ' î˜• '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#e34c26'
        style      = 'plain'
        template   = ' îœ¶ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#563d7c'
        style      = 'plain'
        template   = ' î‰ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#FFD700'
        style      = 'plain'
        template   = ' ï‡… '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#FF4500'
        style      = 'plain'
        template   = ' ğŸ¬ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#2980B9'
        style      = 'plain'
        template   = ' ï¢ƒ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#8E44AD'
        style      = 'plain'
        template   = ' ï '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#F39C12'
        style      = 'plain'
        template   = ' ï€± '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#3B82F6'
        style      = 'plain'
        template   = ' ïŒƒ '
        type       = 'node'

    [[blocks.segments]]
        foreground = '#6A7FEA'
        style      = 'plain'
        template   = '] ï„…'
        type       = 'text'
