version = 4
shell_integration = true
final_space = true
enable_cursor_positioning = true

[transient_prompt]
  template = '[#] ï„… '
  foreground = '#6A7FEA'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = 'î®™ {{ .UserName }} on'
    foreground = '#B4BEFE'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = ' ï„• {{ .Path }} '
    foreground = '#6A7FEA'
    type = 'path'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }} {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{end}}{{ if gt .Behind 0}}â†“{{end}}{{ if gt .Ahead 0 }}â†‘{{end}}{{ if gt .StashCount 0 }} î­‹ {{ .StashCount }}{{ end }} '
    foreground = '#14A5AE'
    powerline_symbol = 'î‚°'
    type = 'git'
    style = 'plain'

  [[blocks.segments]]
    template = '( îˆµ {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} ){{ end }}{{ end }}'
    foreground = '#D0679D'
    type = 'python'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '{{ .CurrentDate | date "15:04:05" }}'
    foreground = '#B8C4C7'
    type = 'time'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{.Icon}} '
    foreground = '#6A7FEA'
    type = 'os'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = 'î¿ '
    foreground = '#cd5e42'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = '['
    foreground = '#6A7FEA'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = ' îˆµ  '
    foreground = '#50C878'
    type = 'python'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜§ '
    foreground = '#7FD5EA'
    type = 'go'
    style = 'plain'

  [[blocks.segments]]
    template = ' îš© '
    foreground = '#342311'
    type = 'zig'
    style = 'plain'

  [[blocks.segments]]
    template = ' îœ˜ '
    foreground = '#6CA35E'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' î¨ '
    foreground = '#D3672C'
    type = 'rust'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜­ '
    foreground = '#422251'
    type = 'elixir'
    style = 'plain'

  [[blocks.segments]]
    template = ' î‰– '
    foreground = '#A51C30'
    type = 'java'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜ˆ '
    foreground = '#75715E'
    type = 'php'
    style = 'plain'

  [[blocks.segments]]
    template = ' <b>K</b> '
    foreground = '#906cff'
    type = 'kotlin'
    style = 'plain'

  [[blocks.segments]]
    template = ' î‘ '
    foreground = '#D32F2F'
    type = 'ruby'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜Ÿ  '
    foreground = '#8A3FFC'
    type = 'haskell'
    style = 'plain'

  [[blocks.segments]]
    template = ' î¿  '
    foreground = '#007ACC'
    type = 'dotnet'
    style = 'plain'

  [[blocks.segments]]
    template = ' î“ '
    foreground = '#D9534F'
    type = 'angular'
    style = 'plain'

  [[blocks.segments]]
    template = ' îº '
    foreground = '#61DAFB'
    type = 'react'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜ î˜ '
    foreground = '#007ACC'
    type = 'cmake'
    style = 'plain'

  [[blocks.segments]]
    template = ' î™º '
    foreground = '#d08770'
    type = 'ocaml'
    style = 'plain'

  [[blocks.segments]]
    template = ' î© '
    foreground = '#4063D8'
    type = 'perl'
    style = 'plain'

  [[blocks.segments]]
    template = ' R '
    foreground = '#ADD8E6'
    type = 'r'
    style = 'plain'

  [[blocks.segments]]
    template = ' îš '
    foreground = '#1E90FF'
    type = 'vala'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜ '
    foreground = '#FFD700'
    type = 'dart'
    style = 'plain'

  [[blocks.segments]]
    template = ' î• '
    foreground = '#FFA500'
    type = 'swift'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜¤ '
    foreground = '#8A2BE2'
    type = 'julia'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜  '
    foreground = '#56B6C2'
    type = 'lua'
    style = 'plain'

  [[blocks.segments]]
    template = 'î '
    foreground = '#F7DF1E'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ğŸ”¥ '
    foreground = '#100e23'
    type = 'mojo'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜¨ '
    foreground = '#007ACC'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ï’‰ '
    foreground = '#E5A50A'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ï‡€ '
    foreground = '#4479A1'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ïŒˆ '
    foreground = '#0db7ed'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' î˜• '
    foreground = '#ff79c6'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' îœ¶ '
    foreground = '#e34c26'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' î‰ '
    foreground = '#563d7c'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ï‡… '
    foreground = '#FFD700'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ğŸ¬ '
    foreground = '#FF4500'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ï¢ƒ '
    foreground = '#2980B9'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ï '
    foreground = '#8E44AD'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ï€± '
    foreground = '#F39C12'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' ïŒƒ '
    foreground = '#3B82F6'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = '] ï„…'
    foreground = '#6A7FEA'
    type = 'text'
    style = 'plain'
